services:
  postgres:
    image: postgres:17
    container_name: weather_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: atlas_weather
      POSTGRES_PASSWORD: abdo2007123@
      POSTGRES_DB: weather_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: